#!/usr/bin/env bash

NAME=nsrecorder
IMAGE=docker.jw4.us/nsrecorder

docker pull ${IMAGE}

docker stop ${NAME} && \
  docker logs ${NAME} &> logs/$(TZ=UTC date +%Y-%m-%d-%H%M-${NAME}.log) && \
  docker rm -v -f ${NAME}

docker run -d \
    --name ${NAME} \
    --hostname ${NAME} \
    --restart=always \
  ${IMAGE} \
    -address localhost:4150 \
    -host localhost

